// Datos iniciales que se insertan en la base de datos la primera vez que
// arranca la aplicación (solo si las tablas están vacías).

// Calendario tributario DIAN — declaración de renta personas naturales,
// año gravable 2025 (vence en 2026). Decreto 2229 de 2023.
// Editable desde la interfaz si la DIAN llega a modificar fechas.
const CALENDARIO_2026 = [
  { digitos: [1, 2], fecha: '2026-08-12' },
  { digitos: [3, 4], fecha: '2026-08-13' },
  { digitos: [5, 6], fecha: '2026-08-14' },
  { digitos: [7, 8], fecha: '2026-08-18' },
  { digitos: [9, 10], fecha: '2026-08-19' },
  { digitos: [11, 12], fecha: '2026-08-20' },
  { digitos: [13, 14], fecha: '2026-08-21' },
  { digitos: [15, 16], fecha: '2026-08-24' },
  { digitos: [17, 18], fecha: '2026-08-25' },
  { digitos: [19, 20], fecha: '2026-08-26' },
  { digitos: [21, 22], fecha: '2026-08-27' },
  { digitos: [23, 24], fecha: '2026-08-28' },
  { digitos: [25, 26], fecha: '2026-08-31' },
  { digitos: [27, 28], fecha: '2026-09-01' },
  { digitos: [29, 30], fecha: '2026-09-02' },
  { digitos: [31, 32], fecha: '2026-09-03' },
  { digitos: [33, 34], fecha: '2026-09-04' },
  { digitos: [35, 36], fecha: '2026-09-07' },
  { digitos: [37, 38], fecha: '2026-09-08' },
  { digitos: [39, 40], fecha: '2026-09-09' },
  { digitos: [41, 42], fecha: '2026-09-10' },
  { digitos: [43, 44], fecha: '2026-09-11' },
  { digitos: [45, 46], fecha: '2026-09-14' },
  { digitos: [47, 48], fecha: '2026-09-15' },
  { digitos: [49, 50], fecha: '2026-09-16' },
  { digitos: [51, 52], fecha: '2026-09-17' },
  { digitos: [53, 54], fecha: '2026-09-18' },
  { digitos: [55, 56], fecha: '2026-09-21' },
  { digitos: [57, 58], fecha: '2026-09-22' },
  { digitos: [59, 60], fecha: '2026-09-23' },
  { digitos: [61, 62], fecha: '2026-09-24' },
  { digitos: [63, 64], fecha: '2026-09-25' },
  { digitos: [65, 66], fecha: '2026-09-28' },
  { digitos: [67, 68], fecha: '2026-10-01' },
  { digitos: [69, 70], fecha: '2026-10-02' },
  { digitos: [71, 72], fecha: '2026-10-05' },
  { digitos: [73, 74], fecha: '2026-10-06' },
  { digitos: [75, 76], fecha: '2026-10-07' },
  { digitos: [77, 78], fecha: '2026-10-08' },
  { digitos: [79, 80], fecha: '2026-10-09' },
  { digitos: [81, 82], fecha: '2026-10-13' },
  { digitos: [83, 84], fecha: '2026-10-14' },
  { digitos: [85, 86], fecha: '2026-10-15' },
  { digitos: [87, 88], fecha: '2026-10-16' },
  { digitos: [89, 90], fecha: '2026-10-19' },
  { digitos: [91, 92], fecha: '2026-10-20' },
  { digitos: [93, 94], fecha: '2026-10-21' },
  { digitos: [95, 96], fecha: '2026-10-22' },
  { digitos: [97, 98], fecha: '2026-10-23' },
  { digitos: [99, 0], fecha: '2026-10-26' },
];

const PLANTILLAS_INICIALES = [
  {
    id: 'empleado',
    nombre: 'Empleado',
    documentos: [
      'Certificado de ingresos y retenciones (formulario 220) del empleador',
      'Certificados de retención en la fuente de otras entidades',
      'Extractos bancarios a 31 de diciembre de 2025',
      'Certificado de aportes a salud y pensión',
      'Certificados de pagos de medicina prepagada',
      'Certificado de intereses de crédito hipotecario o leasing habitacional',
      'Certificado de dependientes (si aplica)',
      'Certificados de cuentas AFC y aportes voluntarios a pensión',
    ],
  },
  {
    id: 'independiente',
    nombre: 'Independiente',
    documentos: [
      'Relación de ingresos facturados durante 2025 (facturas electrónicas)',
      'Certificados de retención en la fuente de clientes',
      'Planillas de pago de seguridad social (PILA) de 2025',
      'Extractos bancarios a 31 de diciembre de 2025',
      'Relación de costos y gastos con soportes',
      'Certificado de intereses de crédito hipotecario (si aplica)',
      'Certificados de cuentas AFC y aportes voluntarios a pensión',
    ],
  },
  {
    id: 'inversionista',
    nombre: 'Con inversiones y patrimonio',
    documentos: [
      'Extractos bancarios y de inversiones a 31 de diciembre de 2025',
      'Certificados de dividendos y participaciones recibidos',
      'Certificados de rendimientos financieros (bancos, fiducias, fondos)',
      'Certificados de retención en la fuente sobre rendimientos de cuentas bancarias',
      'Certificado de tradición de inmuebles y avalúos catastrales 2025',
      'Certificado SIBGA (Sistema de Información Base Gravable de Avalúos) o recibo de pago del impuesto predial',
      'Declaración de renta del año anterior (2024)',
      'Relación de acciones y criptoactivos con su valor a 31 de diciembre',
      'Contratos de arrendamiento e ingresos por arriendos',
      'Certificados de deudas y créditos vigentes a 31 de diciembre',
    ],
  },
];

const CONFIG_INICIAL = {
  asunto: 'Recordatorio: tu declaración de renta vence el {{vencimiento}}',
  cuerpo: [
    '<p>Hola <strong>{{nombre}}</strong>,</p>',
    '<p>Te recordamos que la fecha límite para presentar tu declaración de renta ',
    '(año gravable 2025) es el <strong>{{vencimiento}}</strong>, según los dos últimos ',
    'dígitos de tu documento ({{digitos}}).</p>',
    '<p>Para preparar tu declaración a tiempo, por favor ten listos los siguientes documentos:</p>',
    '{{documentos}}',
    '<p>Si tienes alguna duda o necesitas ayuda para conseguir alguno de estos documentos, ',
    'responde a este correo y con gusto te orientamos.</p>',
    '<p>Cordial saludo,</p>',
    '<p><strong>{{remitente}}</strong></p>',
  ].join('\n'),
  // Invitación al portal de documentos (Fase 2): correo aparte del
  // recordatorio, con el enlace personal {{portal}} de cada cliente.
  asunto_portal: 'Sube los documentos de tu declaración de renta en tu portal personal',
  cuerpo_portal: [
    '<p>Hola <strong>{{nombre}}</strong>,</p>',
    '<p>Ya está disponible tu portal personal para la declaración de renta ',
    '(año gravable 2025). Allí puedes subir, antes del <strong>{{vencimiento}}</strong>, ',
    'cada uno de los documentos de tu lista:</p>',
    '{{documentos}}',
    '<p style="text-align:center;margin:24px 0;"><a href="{{portal}}" ',
    'style="background:#152a45;color:#ffffff;text-decoration:none;padding:12px 28px;',
    'border-radius:6px;display:inline-block;">Subir mis documentos</a></p>',
    '<p>El enlace es personal, no lo compartas. Revisaremos cada documento y te ',
    'avisaremos por este medio si alguno necesita corrección.</p>',
    '<p>Si tienes alguna duda, responde a este correo y con gusto te orientamos.</p>',
    '<p>Cordial saludo,</p>',
    '<p><strong>{{remitente}}</strong></p>',
  ].join('\n'),
  // Novedades del portal: correo que explica al cliente todo lo que puede
  // hacer en su portal (subir documentos, agregar otros, clave DIAN, editar
  // sus datos, descargar sus soportes y recuperar el enlace con la cédula).
  asunto_novedades: 'Novedades de su portal de documentos — declaración de renta',
  cuerpo_novedades: [
    '<div style="background:#fbf8f6;padding:24px 12px;font-family:\'Segoe UI\',system-ui,-apple-system,sans-serif;font-size:15px;line-height:1.5;">',
    '<div style="max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #e3ddd4;border-top:4px solid #c39a3b;border-radius:10px;padding:28px 32px;">',
    '<img src="https://declaraciones-renta-pn.repolite.link/logo_DM_120.png" width="60" height="60" alt="DM" style="border-radius:50%;display:block;margin:0 auto 8px;">',
    '<h2 style="color:#152a45;font-size:18px;margin:0 0 12px;text-align:center;">Su portal de documentos, ahora más completo</h2>',
    '<p style="color:#2b3440;">Hola <strong>{{nombre}}</strong>,</p>',
    '<p style="color:#2b3440;">Para su declaración de renta (año gravable 2025, con plazo hasta el ',
    '<strong>{{vencimiento}}</strong>) usted cuenta con un portal personal. Esto es lo que puede hacer allí:</p>',
    '<ul style="color:#2b3440;padding-left:20px;">',
    '<li style="margin-bottom:8px;"><strong>Subir sus documentos:</strong> cargue cada documento de su lista ',
    '(PDF, foto o documento de Office, máx. 15 MB). Los revisamos y le avisamos por correo si algo necesita corrección.</li>',
    '<li style="margin-bottom:8px;"><strong>Agregar otros documentos:</strong> si tiene certificados de varias ',
    'entidades (deudas, cuentas, tarjetas, billeteras digitales u otro vehículo), use el botón ',
    '"Agregar otro documento" y escríbale un nombre claro.</li>',
    '<li style="margin-bottom:8px;"><strong>Dejar su clave de la DIAN:</strong> la necesitamos para presentar su ',
    'declaración. Se guarda cifrada, el portal nunca la muestra y solo su contadora puede consultarla.</li>',
    '<li style="margin-bottom:8px;"><strong>Mantener sus datos al día:</strong> con el lápiz junto a su nombre ',
    'puede corregir su correo y su celular.</li>',
    '<li style="margin-bottom:8px;"><strong>Descargar sus soportes:</strong> cuando su declaración quede presentada, ',
    'allí mismo encontrará la declaración, el anexo de renta y el recibo de pago (si aplica).</li>',
    '</ul>',
    '<p style="text-align:center;margin:24px 0;"><a href="{{portal}}" ',
    'style="background:#152a45;color:#ffffff;text-decoration:none;padding:12px 28px;border-radius:6px;display:inline-block;">Entrar a mi portal</a></p>',
    '<p style="color:#2b3440;">¿Perdió este correo o el enlace? Entre a ',
    '<a href="{{recuperar}}" style="color:#152a45;">{{recuperar}}</a>, escriba su número de cédula ',
    'y se lo reenviamos al correo que tenemos registrado.</p>',
    '<p style="color:#2b3440;">El enlace es personal: no lo comparta con nadie.</p>',
    '<p style="color:#2b3440;margin-bottom:0;">Cordial saludo,<br><strong style="color:#152a45;">{{remitente}}</strong></p>',
    '</div></div>',
  ].join('\n'),
  remitente: '',
  // Correo interno (el de Daniela) al que llegan los avisos de subidas al
  // portal y la alerta diaria de vencimientos próximos. Vacío = sin avisos.
  correo_avisos: '',
};

module.exports = { CALENDARIO_2026, PLANTILLAS_INICIALES, CONFIG_INICIAL };
