// Mapa casilla → etiqueta del Formulario 210 oficial, para mostrarlo en
// pantalla (PasoFormulario210.jsx). Mismas etiquetas que ya usa
// formularioDianExcel.js para el Excel exportable (fuente: FORMULARIO_210.md,
// volcado real del .xlsm de referencia) — este archivo NO repite las
// posiciones de celda (eso es exclusivo del export a Excel, donde sí
// importa la coordenada exacta), solo el texto y el orden de despliegue.
export const SECCIONES_FORMULARIO_210 = [
  {
    titulo: 'Identificación',
    casillas: [
      { casilla: 1, etiqueta: 'Año' },
      { casilla: 5, etiqueta: 'Número de Identificación Tributaria (NIT)' },
      { casilla: 6, etiqueta: 'DV' },
      { casilla: 7, etiqueta: 'Primer apellido' },
      { casilla: 8, etiqueta: 'Segundo apellido' },
      { casilla: 9, etiqueta: 'Primer nombre' },
      { casilla: 10, etiqueta: 'Otros nombres' },
      { casilla: 12, etiqueta: 'Cód. Dirección Seccional' },
      { casilla: 24, etiqueta: 'Actividad económica principal' },
      { casilla: 28, etiqueta: '1% compras con factura electrónica' },
    ],
  },
  {
    titulo: 'Patrimonio',
    casillas: [
      { casilla: 29, etiqueta: 'Total patrimonio bruto' },
      { casilla: 30, etiqueta: 'Deudas' },
      { casilla: 31, etiqueta: 'Total patrimonio líquido' },
    ],
  },
  {
    titulo: 'Cédula general — rentas de trabajo',
    casillas: [
      { casilla: 32, etiqueta: 'Ingresos brutos' },
      { casilla: 33, etiqueta: 'Ingresos no constitutivos de renta' },
      { casilla: 34, etiqueta: 'Renta líquida' },
      { casilla: 35, etiqueta: 'Rentas exentas — aportes voluntarios AFC/FVP/AVC' },
      { casilla: 36, etiqueta: 'Otras rentas exentas' },
      { casilla: 37, etiqueta: 'Total rentas exentas' },
      { casilla: 38, etiqueta: 'Deducciones imputables — intereses de vivienda' },
      { casilla: 39, etiqueta: 'Otras deducciones imputables' },
      { casilla: 40, etiqueta: 'Total deducciones imputables' },
      { casilla: 41, etiqueta: 'Rentas exentas y deducciones imputables (limitadas)' },
      { casilla: 42, etiqueta: 'Renta líquida ordinaria' },
    ],
  },
  {
    titulo: 'Cédula general — rentas de honorarios (sin relación laboral)',
    casillas: [
      { casilla: 43, etiqueta: 'Ingresos brutos' },
      { casilla: 44, etiqueta: 'Ingresos no constitutivos de renta' },
      { casilla: 45, etiqueta: 'Costos y deducciones procedentes' },
      { casilla: 46, etiqueta: 'Renta líquida' },
      { casilla: 47, etiqueta: 'Rentas exentas — aportes voluntarios AFC/FVP/AVC' },
      { casilla: 48, etiqueta: 'Otras rentas exentas' },
      { casilla: 49, etiqueta: 'Total rentas exentas' },
      { casilla: 50, etiqueta: 'Deducciones imputables — intereses de vivienda' },
      { casilla: 51, etiqueta: 'Otras deducciones imputables' },
      { casilla: 52, etiqueta: 'Total deducciones imputables' },
      { casilla: 53, etiqueta: 'Rentas exentas y deducciones imputables (limitadas)' },
      { casilla: 54, etiqueta: 'Renta líquida ordinaria del ejercicio' },
      { casilla: 55, etiqueta: 'Pérdida líquida del ejercicio' },
      { casilla: 56, etiqueta: 'Compensación por pérdidas' },
      { casilla: 57, etiqueta: 'Renta líquida ordinaria' },
    ],
  },
  {
    titulo: 'Cédula general — rentas de capital',
    casillas: [
      { casilla: 58, etiqueta: 'Ingresos brutos' },
      { casilla: 59, etiqueta: 'Ingresos no constitutivos de renta' },
      { casilla: 60, etiqueta: 'Costos y deducciones procedentes' },
      { casilla: 61, etiqueta: 'Renta líquida' },
      { casilla: 62, etiqueta: 'Rentas líquidas pasivas — ECE' },
      { casilla: 63, etiqueta: 'Rentas exentas — aportes voluntarios AFC/FVP/AVC' },
      { casilla: 64, etiqueta: 'Otras rentas exentas' },
      { casilla: 65, etiqueta: 'Total rentas exentas' },
      { casilla: 66, etiqueta: 'Deducciones imputables — intereses de vivienda' },
      { casilla: 67, etiqueta: 'Otras deducciones imputables' },
      { casilla: 68, etiqueta: 'Total deducciones imputables' },
      { casilla: 69, etiqueta: 'Rentas exentas y deducciones imputables (limitadas)' },
      { casilla: 70, etiqueta: 'Renta líquida ordinaria del ejercicio' },
      { casilla: 71, etiqueta: 'Pérdida líquida del ejercicio' },
      { casilla: 72, etiqueta: 'Compensación por pérdidas' },
      { casilla: 73, etiqueta: 'Renta líquida ordinaria' },
    ],
  },
  {
    titulo: 'Cédula general — rentas no laborales',
    casillas: [
      { casilla: 74, etiqueta: 'Ingresos brutos' },
      { casilla: 75, etiqueta: 'Devoluciones, rebajas y descuentos' },
      { casilla: 76, etiqueta: 'Ingresos no constitutivos de renta' },
      { casilla: 77, etiqueta: 'Costos y deducciones procedentes' },
      { casilla: 78, etiqueta: 'Renta líquida' },
      { casilla: 79, etiqueta: 'Rentas líquidas pasivas — ECE' },
      { casilla: 80, etiqueta: 'Rentas exentas — aportes voluntarios AFC/FVP/AVC' },
      { casilla: 81, etiqueta: 'Otras rentas exentas' },
      { casilla: 82, etiqueta: 'Total rentas exentas' },
      { casilla: 83, etiqueta: 'Deducciones imputables — intereses de vivienda' },
      { casilla: 84, etiqueta: 'Otras deducciones imputables' },
      { casilla: 85, etiqueta: 'Total deducciones imputables' },
      { casilla: 86, etiqueta: 'Rentas exentas y deducciones imputables (limitadas)' },
      { casilla: 87, etiqueta: 'Renta líquida ordinaria del ejercicio' },
      { casilla: 88, etiqueta: 'Pérdida líquida del ejercicio' },
      { casilla: 89, etiqueta: 'Compensación por pérdidas' },
      { casilla: 90, etiqueta: 'Renta líquida ordinaria' },
    ],
  },
  {
    titulo: 'Cédula general — consolidado',
    casillas: [
      { casilla: 91, etiqueta: 'Renta líquida cédula general' },
      { casilla: 92, etiqueta: 'Rentas exentas y deducciones imputables (limitadas)' },
      { casilla: 93, etiqueta: 'Renta líquida ordinaria cédula general' },
      { casilla: 94, etiqueta: 'Compensación pérdidas año 2018 y anteriores' },
      { casilla: 95, etiqueta: 'Compensación por exceso de renta presuntiva' },
      { casilla: 96, etiqueta: 'Rentas gravables (comparación patrimonial)' },
      { casilla: 97, etiqueta: 'Renta líquida gravable cédula general' },
      { casilla: 98, etiqueta: 'Renta presuntiva' },
    ],
  },
  {
    titulo: 'Cédula de pensiones',
    casillas: [
      { casilla: 99, etiqueta: 'Ingresos brutos por rentas de pensiones del país y del exterior' },
      { casilla: 100, etiqueta: 'Ingresos no constitutivos de renta' },
      { casilla: 101, etiqueta: 'Renta líquida (99-100)' },
      { casilla: 102, etiqueta: 'Rentas exentas de pensiones' },
      { casilla: 103, etiqueta: 'Renta líquida gravable cédula de pensiones (101-102)' },
    ],
  },
  {
    titulo: 'Cédula de dividendos y participaciones',
    casillas: [
      { casilla: 104, etiqueta: 'Dividendos y/o participaciones año 2016 y anteriores, y otros' },
      { casilla: 105, etiqueta: 'Ingresos no constitutivos de renta' },
      { casilla: 106, etiqueta: 'Renta líquida ordinaria año 2016 y anteriores (104-105)' },
      { casilla: 107, etiqueta: '1a. Subcédula 2017 y siguientes (numeral 3 art. 49 ET)' },
      { casilla: 108, etiqueta: '2a. Subcédula 2017 y siguientes (parágrafo 2° art. 49 ET)' },
      { casilla: 109, etiqueta: 'Renta líquida pasiva dividendos — ECE y/o recibidos del exterior' },
      { casilla: 110, etiqueta: 'Rentas exentas de la casilla 109' },
    ],
  },
  {
    titulo: 'Renta líquida gravable total',
    casillas: [{ casilla: 111, etiqueta: 'Cédula general, renta presuntiva, pensiones y dividendos (Art. 241 ET)' }],
  },
  {
    titulo: 'Ganancias ocasionales',
    casillas: [
      { casilla: 112, etiqueta: 'Ingresos por ganancias ocasionales del país y del exterior' },
      { casilla: 113, etiqueta: 'Costos por ganancias ocasionales' },
      { casilla: 114, etiqueta: 'Ganancias ocasionales no gravadas y exentas' },
      { casilla: 115, etiqueta: 'Ganancias ocasionales gravables (112-113-114)' },
    ],
  },
  {
    titulo: 'Liquidación privada — impuesto',
    casillas: [
      { casilla: 116, etiqueta: 'Impuesto — cédula general, pensiones y dividendos (base 111)' },
      { casilla: 117, etiqueta: 'Impuesto — renta presuntiva (base 111)' },
      { casilla: 118, etiqueta: 'Dividendos y participaciones 2017+, 2a subcédula (Art. 240 ET)' },
      { casilla: 119, etiqueta: 'Dividendos y participaciones año 2016 (base 106)' },
      { casilla: 120, etiqueta: 'Dividendos y participaciones recibidos del exterior (base 109-110)' },
      { casilla: 121, etiqueta: 'Total impuesto sobre las rentas líquidas gravables (116+117+118+119+120)' },
    ],
  },
  {
    titulo: 'Descuentos',
    casillas: [
      { casilla: 122, etiqueta: 'Impuestos pagados en el exterior' },
      { casilla: 123, etiqueta: 'Donaciones' },
      { casilla: 124, etiqueta: 'Dividendos, participaciones y otros' },
      { casilla: 125, etiqueta: 'Total descuentos tributarios (122+123+124)' },
    ],
  },
  {
    titulo: 'Liquidación privada — impuesto neto y anticipo',
    casillas: [
      { casilla: 126, etiqueta: 'Impuesto neto de renta (121-125)' },
      { casilla: 127, etiqueta: 'Impuesto de ganancias ocasionales (casilla 115 por tarifa)' },
      { casilla: 128, etiqueta: 'Descuento por impuestos pagados en el exterior por ganancias ocasionales' },
      { casilla: 129, etiqueta: 'Total impuesto a cargo (126+127-128)' },
      { casilla: 130, etiqueta: 'Anticipo renta liquidado año gravable anterior' },
      { casilla: 131, etiqueta: 'Saldo a favor año anterior sin solicitud de devolución' },
      { casilla: 132, etiqueta: 'Retenciones año gravable a declarar' },
      { casilla: 133, etiqueta: 'Anticipo renta para el año gravable siguiente' },
      { casilla: 134, etiqueta: 'Saldo a pagar por impuesto (129+133-130-131-132)' },
      { casilla: 135, etiqueta: 'Sanciones' },
      { casilla: 136, etiqueta: 'Total saldo a pagar (129+133+135-130-131-132)' },
      { casilla: 137, etiqueta: 'Total saldo a favor (130+131+132-129-133-135)' },
    ],
  },
  {
    titulo: 'Dependientes',
    casillas: [
      { casilla: 138, etiqueta: 'Número de dependientes económicos' },
      { casilla: 139, etiqueta: 'Adición por dependientes a la casilla 92' },
    ],
  },
];
